import: 
  - ~/.themes/alacritty-dracula/dracula.yml
  #- ~/.themes/alacritty-omni/omni.yml
  
#######################################
##              ENVS                 ##
#######################################

env:
  TERM: xterm-256color
  #TERM: alacritty

#######################################
##              WINDOW               ##
#######################################

window:

  decorations: none # 'none' para retirar bordas, etc... / 'full' mantem tudo

  dimensions:
   columns: 98
   lines: 25

  padding:
    x: 5
    y: 1

  class:
    instance: Alacritty
    general: Alacritty

  # opacidade da janela
  opacity: 1

  dynamic_title: true
  dynamic_padding: false

#######################################
##             SCROLL                ##
#######################################

scrolling:
  history: 10000
  multiplier: 5 # speed do scroll

#######################################
##             FONTS                 ##
#######################################

font:
  normal:
    family: MesloLGS NF
    style: Bold

  bold:
    family: MesloLGS NF
    style: Bold

  italic:
    family: MesloLGS NF
    style: Italic

  bold_italic:
    family: MesloLGS NF
    style: Bold Italic

  size: 17

  builtin_box_drawing: true

draw_bold_text_with_bright_colors: true


#######################################
##             CURSOR                ##
#######################################

cursor:
  style:
    shape: Beam
    blinking: Off
    # blink-interval: 750
  unfocused_hollow: true


#######################################
##             URL OPEN              ##
#######################################

url:
  launcher:  
    program: open

#######################################
##             SHELL                 ##
#######################################

shell:
 program: /usr/bin/zsh

#######################################
##             DIRECTORY             ##
#######################################

working_directory: None # muda diretório padrão de inicialização

mouse_bindings:
  - { mouse: Right,                 action: ExpandSelection }
  - { mouse: Right,  mods: Control, action: ExpandSelection }
  - { mouse: Middle, mode: ~Vi,     action: PasteSelection  }

key_bindings:

  - { key: V,              mods: Control|Shift, mode: ~Vi,        action: Paste            }
  - { key: C,              mods: Control|Shift,                   action: Copy             }
  - { key: F,              mods: Control|Shift, mode: ~Search,    action: SearchForward    }
  - { key: B,              mods: Control|Shift, mode: ~Search,    action: SearchBackward   }
  - { key: N,                           mode: Vi|~Search, action: SearchNext              }
  - { key: N,      mods: Shift,         mode: Vi|~Search, action: SearchPrevious          }
  - { key: C,              mods: Control|Shift, mode: Vi|~Search, action: ClearSelection   }
  - { key: Insert,         mods: Shift,                           action: PasteSelection   }
  - { key: Key0,           mods: Control,                         action: ResetFontSize    }
  - { key: Equals,         mods: Control,                         action: IncreaseFontSize }
  - { key: Plus,           mods: Control,                         action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control,                         action: IncreaseFontSize }
  - { key: Minus,          mods: Control,                         action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control,                         action: DecreaseFontSize }
  - { key: Paste,                                       action: Paste          }
  - { key: Copy,                                        action: Copy           }
  - { key: L,         mods: Control,                    action: ClearLogNotice }
  - { key: L,         mods: Control, mode: ~Vi|~Search, chars: "\x0c"          }
  - { key: PageUp,    mods: Shift,   mode: ~Alt,        action: ScrollPageUp,  }
  - { key: PageDown,  mods: Shift,   mode: ~Alt,        action: ScrollPageDown }
  - { key: Home,      mods: Shift,   mode: ~Alt,        action: ScrollToTop,   }
  - { key: End,       mods: Shift,   mode: ~Alt,        action: ScrollToBottom }


  # Search Mode
  - { key: Return,                mode: Search|Vi,  action: SearchConfirm         }
  - { key: Escape,                mode: Search,     action: SearchCancel          }
  - { key: C,      mods: Control, mode: Search,     action: SearchCancel          }
  - { key: U,      mods: Control, mode: Search,     action: SearchClear           }
  - { key: W,      mods: Control, mode: Search,     action: SearchDeleteWord      }
  - { key: P,      mods: Control, mode: Search,     action: SearchHistoryPrevious }
  - { key: N,      mods: Control, mode: Search,     action: SearchHistoryNext     }
  - { key: Up,                    mode: Search,     action: SearchHistoryPrevious }
  - { key: Down,                  mode: Search,     action: SearchHistoryNext     }
  - { key: Return,                mode: Search|~Vi, action: SearchFocusNext       }
  - { key: Return, mods: Shift,   mode: Search|~Vi, action: SearchFocusPrevious   }

colors:

  search:

    matches:
     foreground: '#000000'
     background: '#D8CE00'
    focused_match:
     foreground: '#ffffff'
     background: '#00A32E'

  footer_bar:
   background: '#c5c8c6'
   foreground: '#1d1f21'

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: false
